# Generated by Django 5.2.1 on 2025-05-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodsongmap',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.mood'),
        ),
        migrations.AlterField(
            model_name='moodsongmap',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='core.song'),
        ),
        migrations.AlterField(
            model_name='usermoodhistory',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='core.mood'),
        ),
        migrations.AlterField(
            model_name='usermoodhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
