# Generated by Django 5.2.1 on 2025-05-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moodsongmap_mood_alter_moodsongmap_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='moods',
            field=models.ManyToManyField(related_name='songs', through='core.MoodSongMap', to='core.mood'),
        ),
        migrations.AlterField(
            model_name='moodsongmap',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_song_maps', to='core.mood'),
        ),
        migrations.AlterField(
            model_name='moodsongmap',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_song_maps', to='core.song'),
        ),
    ]
